create schema ADDS authorization ADMIN;

drop table ADDS.OGLASI;

drop sequence ADDS.OGLASI_SEQ;

CREATE SEQUENCE ADDS.OGLASI_SEQ;

create table ADDS.OGLASI (
ID INT PRIMARY KEY,
SIFRA VARCHAR(20),
NASLOV VARCHAR(500),
OPIS VARCHAR(4000),
CIJENA_KN INT (10),
CIJENA_EURO INT (10),
URL VARCHAR(500),
SLIKA_URL VARCHAR(500),
SITE INT,
DATUM_OBJAVE TIMESTAMP,
DATUM TIMESTAMP
)